cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

coupons/urls.py
from django.urls import path
from . import views


app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _


urlpatterns = i18n_patterns (
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
)

orders/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

shop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label=_('Quantity'))
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

    

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm
from shop.recommender import Recommender


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'override': True})
    coupon_apply_form = CouponApplyForm()
    r = Recommender()
    cart_products = [item['product'] for item in cart]
    recommended_products = r.suggest_products_for(cart_products, max_results=4)
    return render(request, 'cart/detail.html', {'cart': cart, 'coupon_apply_form': coupon_apply_form, 'recommended_products': recommended_products})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}
  {% trans "Your shopping cart" %}
{% endblock %}

{% block content %}
  <h1>{% trans "Your shopping cart" %}</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>{% trans "Image" %}</th>
        <th>{% trans "Product" %}</th>
        <th>{% trans "Quantity" %}</th>
        <th>{% trans "Remove" %}</th>
        <th>{% trans "Unit price" %}</th>
        <th>{% trans "Price" %}</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}
                {% else %}{% static "img/no_image.png" %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url "cart:cart_add" product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type="submit" value="Update">
                {% csrf_token %}
              </form>
            </td>
            <td>
              <form action="{% url "cart:cart_remove" product.id %}" method="post">
                <input type="submit" value="{% trans "Remove" %}">
                {% csrf_token %}
              </form>
            </td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      {% if cart.coupon %}
        <tr class="subtotal">
          <td>{% trans "Subtotal" %}</td>
          <td colspan="4"></td>
          <td class="num">${{ cart.get_total_price|floatformat:2 }}</td>
        </tr>
        <tr>
          {% blocktrans with code=cart.coupon.code discount=cart.coupon.discount %}
            <td>"{{ code }}" coupon ({{ discount }}% off)</td>
          {% endblocktrans %}
          <td colspan="4"></td>
          <td class="num neg">
            - ${{ cart.get_discount|floatformat:2 }}
          </td>
        </tr>
      {% endif %}
      <tr class="total">
        <td>{% trans "Total" %}</td>
        <td colspan="4"></td>
        <td class="num">
          ${{ cart.get_total_price_after_discount|floatformat:2 }}
        </td>
      </tr>
    </tbody>
  </table>

  {% if recommended_products %}
    <div class="recommendations cart">
      <h3>{% trans "People who bought this also bought" %}</h3>
      {% for p in recommended_products %}
        <div class="item">
          <a href="{{ p.get_absolute_url }}">
            <img src="{% if p.image %}{{ p.image.url }}{% else %}
            {% static "img/no_image.png" %}{% endif %}">
          </a>
          <p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
        </div>
      {% endfor %}
    </div>
  {% endif %}

  <p>{% trans "Apply a coupon" %}:</p>
  <form action="{% url "coupons:apply" %}" method="post">
    {{ coupon_apply_form }}
    <input type="submit" value="Apply">
    {% csrf_token %}
  </form>

  <p class="text-right">
    <a href="{% url "shop:product_list" %}" class="button light">{% trans "Continue shopping" %}</a>
    <a href="{% url "orders:order_create" %}" class="button">
      {% trans "Checkout" %}
    </a>
  </p>
{% endblock %}